### ISSUE TITLE
Implement a puzzle shaped search button

### ISSUE THREAD

**Issue by kevinlaw91** [ViviGroupe/vivicrew-web#1]
Cosmetic requirement
- Puzzle shaped search button

**Comment by kevinlaw91** [comment]
@ohjacking, Regarding the puzzle shaped search button, it is doable but requires few hours of research on css and svg and tweaking.
Maybe we can focus on other important things first and readdress this requirement later?

**This is currently how it looks like:**
![searchbox](https://cloud.githubusercontent.com/assets/4179182/25481385/814e123a-2b7f-11e7-9d4c-852f6ea49d8e.JPG)

If this is acceptable, we can move on to other thing first.

**Comment by ohjacking** [comment]
yup move on to other stuff first. leave it that way first its okay.
