### ISSUE TITLE
Amendment on Sign Up Page

### ISSUE THREAD

**Issue by ohjacking** [ViviGroupe/vivicrew-web#25]
1)the 'sign up bar' can be lengthened to the same width as bar above. u can take airbnb as example.
![screen shot 2017-05-24 at 2 05 48 pm](https://cloud.githubusercontent.com/assets/28042946/26389020/4b50e39a-408a-11e7-9717-de304acc8b45.png)

and the 'already a user, sign in' can go below it. 

2) inside burger list, the bar should span the whole length row, so that when u press not exactly on the word, the system will respond too.

3) As for the hp-old-version-browser-cant-use issue, whats ur advice on this? pretty clueless.

**Comment by kevinlaw91** [comment]
Fixed:
1. Button size (67cc285282c08561ddfcee60005eb88f765a17b5)
2. Hamburger menu items size (dc1f74911fbdab3d58aebeefc9a558dd05763995)
