### ISSUE TITLE
Search result page paging

### ISSUE THREAD

**Issue by kevinlaw91** [ViviGroupe/vivicrew-web#3]
-  Max result: 9
-  Paging control: left right arrow button

**Comment by kevinlaw91** [comment]
@ohjacking ,

There will be some minor to moderate performance hit if show 18 results max. I would suggest only 6 or 12, since majority user will only read top result anyways, so we can free up some server load.

Why not 18 results each page:
-  Server has to serve 18 jpg files of tour promo pic
-  Slower page load for user due to download many images
-  Need to query database name, host, description, rating for each of them

**Comment by kevinlaw91** [comment]
@cd11103, how do you think?

**Comment by cd11103** [comment]
@ohjacking , @kevinlaw91 
Maybe 9 is already enough for each pagination

**Comment by ohjacking** [comment]
@kevinlaw91 @cd11103 
ok we follow yong suggestion then, 9 each page, and only left right arrow.
