### ISSUE TITLE
Tile List aka Filter Page

### ISSUE THREAD

**Issue by hancin622** [ViviGroupe/vivicrew-web#30]
[2.1TileListAkaFilterPage.pdf](https://github.com/ViviGroupe/vivicrew-web/files/1060404/2.1TileListAkaFilterPage.pdf)

**Comment by cd11103** [comment]
![tile list](https://user-images.githubusercontent.com/13926253/26920606-178e0770-4c6c-11e7-9ce7-d3b12cb9e956.PNG)

**Comment by hancin622** [comment]
Hi Kevin, we miss out on this in the filtering section. Addition of sorting:
1) Ratings
2) Number of views
3) Price - Low to High
4) Price - High to Low
5) A-Z
6) Z-A

**Comment by hancin622** [comment]
Tile List as of 1st page. Use name and place instead of tour title.

**Comment by hancin622** [comment]
![26920606-178e0770-4c6c-11e7-9ce7-d3b12cb9e956 2](https://user-images.githubusercontent.com/28045480/27084524-d0651d22-507e-11e7-958e-e01da96efac0.PNG)

**Comment by kevinlaw91** [comment]
Fixed in 8c7ce92bb41fbf6f0ea894b08efdd47d25217b3e and 9f35e8a6874d57fde5242b642233d88a563cc22c
